name: On nightly

on:
  workflow_dispatch:

jobs:

  test_full_model:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    if: always()  # This ensures the job runs regardless of success or failure of `nightly_tests`
    with:
      test_mark: 'model_test'