name: On push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit

  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit

  build-and-test:
    needs: [pre-commit, spdx]
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      build_options: |
        [
          {"runs-on": "tt-beta-ubuntu-2204-n150-large-stable", "name": "run", "dir": "./tests/jax/single_chip"},
          {"runs-on": "tt-beta-ubuntu-2204-n300-large-stable", "name": "run", "dir": "./tests/jax/multi_chip/n300"},
          {"runs-on": "llmbox", "name": "run_4", "dir": "./tests/jax/multi_chip/llmbox/4_devices"},
          {"runs-on": "llmbox", "name": "run_8", "dir": "./tests/jax/multi_chip/llmbox/8_devices"}
        ]
