name: On PR

on:
  workflow_dispatch:
    inputs:
      mlir_override:
        description: 'Git SHA of commit in tenstorrent/tt-mlir'
        required: false
        type: string
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.mlir_override }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit

  check-files:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if ignored files are modified
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          all_match=true
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only --repo ${{ github.repository }})
            for file in $CHANGED_FILES;
            do
              if [[ ! $file =~ ^.*\.(md|gitignore)$ && $file != *"LICENSE"* ]]; then
                all_match=false
                break
              fi
            done
          else
            all_match=false
          fi
          if [ "$all_match" = true ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "> --- Build is skipped. Files in PR:"
            echo "$CHANGED_FILES"
            echo "< ---"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "> Build is required."
          fi

  build-image:
    needs: [ pre-commit, spdx, check-files ]
    if: needs.check-files.outputs.skip == 'false'
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      mlir_override: ${{ inputs.mlir_override}}

  build-torch-wheels:
    needs: [ check-files, build-image ]
    if: needs.check-files.outputs.skip == 'false'
    uses: ./.github/workflows/build-torch-wheels.yml
    secrets: inherit
    with:
      torch_version: '2.7.0'

  check-all-green:
    if: always()
    needs:
      - pre-commit
      - spdx
      - check-files
      - build-torch-wheels
    runs-on: Ubuntu-latest
    steps:
    - name: Check if the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build-image, build-ttxla, test
        jobs: ${{ toJSON(needs) }}
