name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: "Release id to publish"
        required: true
      package_version:
        description: "Version of the package"
        required: true
      build_run_id:
        description: "Run ID for the build_package.yml workflow that triggered this workflow"
        required: true

jobs:
  publish_release:
    name: "Publish release"
    runs-on: ubuntu-20.04
    steps:
      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@46913fa2b3f7edc7345ae3c17f6d1b093a54916d # v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        with:
          release_id: ${{ github.event.inputs.release_id }}

      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          # Get all history. Otherwise the latest-snapshot branch can't be
          # fast-forwarded.
          fetch-depth: 0

      - name: Updating latest-snapshot branch
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: latest-snapshot
          force: true
